/**
 * Icon map — resolves lucide icon names (strings from spoke manifests)
 * to actual lucide-react components.
 *
 * Maps ~100 common icons. Unknown icon names fall back to Box.
 */

import type { LucideIcon } from 'lucide-react'
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  BarChart,
  BarChart2,
  BarChart3,
  Bell,
  Bookmark,
  Box,
  Briefcase,
  Building,
  Building2,
  Calendar,
  CalendarDays,
  Check,
  CheckCircle,
  CheckSquare,
  ChevronDown,
  ChevronRight,
  Circle,
  Clock,
  Cloud,
  Code,
  Coins,
  Compass,
  CreditCard,
  Database,
  DollarSign,
  Download,
  Edit,
  ExternalLink,
  Eye,
  File,
  FileText,
  Filter,
  Flag,
  Folder,
  Gift,
  Globe,
  GripVertical,
  Hash,
  Heart,
  Home,
  Image,
  Inbox,
  Info,
  Key,
  Layers,
  LayoutDashboard,
  LineChart,
  Link,
  List,
  Lock,
  LogOut,
  Mail,
  Map,
  MapPin,
  Menu,
  MessageCircle,
  MessageSquare,
  Minus,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Package,
  Paperclip,
  Pencil,
  Phone,
  PieChart,
  Pin,
  Plus,
  Power,
  Printer,
  RefreshCw,
  Repeat,
  Search,
  Send,
  Settings,
  Share,
  Shield,
  ShoppingCart,
  Slash,
  Smartphone,
  Star,
  Sun,
  Table,
  Tag,
  Target,
  ThumbsUp,
  Trash,
  TrendingDown,
  TrendingUp,
  Truck,
  Upload,
  User,
  UserCircle,
  Users,
  Wallet,
  Zap,
} from 'lucide-react'

const ICON_MAP: Record<string, LucideIcon> = {
  'activity': Activity,
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'archive': Archive,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'bar-chart': BarChart,
  'bar-chart-2': BarChart2,
  'bar-chart-3': BarChart3,
  'bell': Bell,
  'bookmark': Bookmark,
  'box': Box,
  'briefcase': Briefcase,
  'building': Building,
  'building-2': Building2,
  'calendar': Calendar,
  'calendar-days': CalendarDays,
  'check': Check,
  'check-circle': CheckCircle,
  'check-square': CheckSquare,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'circle': Circle,
  'clock': Clock,
  'cloud': Cloud,
  'code': Code,
  'coins': Coins,
  'compass': Compass,
  'credit-card': CreditCard,
  'database': Database,
  'dollar-sign': DollarSign,
  'download': Download,
  'edit': Edit,
  'external-link': ExternalLink,
  'eye': Eye,
  'file': File,
  'file-text': FileText,
  'filter': Filter,
  'flag': Flag,
  'folder': Folder,
  'gift': Gift,
  'globe': Globe,
  'grip-vertical': GripVertical,
  'hash': Hash,
  'heart': Heart,
  'home': Home,
  'image': Image,
  'inbox': Inbox,
  'info': Info,
  'key': Key,
  'layers': Layers,
  'layout-dashboard': LayoutDashboard,
  'line-chart': LineChart,
  'link': Link,
  'list': List,
  'lock': Lock,
  'log-out': LogOut,
  'mail': Mail,
  'map': Map,
  'map-pin': MapPin,
  'menu': Menu,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  'minus': Minus,
  'monitor': Monitor,
  'moon': Moon,
  'more-horizontal': MoreHorizontal,
  'more-vertical': MoreVertical,
  'package': Package,
  'paperclip': Paperclip,
  'pencil': Pencil,
  'phone': Phone,
  'pie-chart': PieChart,
  'pin': Pin,
  'plus': Plus,
  'power': Power,
  'printer': Printer,
  'refresh-cw': RefreshCw,
  'repeat': Repeat,
  'search': Search,
  'send': Send,
  'settings': Settings,
  'share': Share,
  'shield': Shield,
  'shopping-cart': ShoppingCart,
  'slash': Slash,
  'smartphone': Smartphone,
  'star': Star,
  'sun': Sun,
  'table': Table,
  'tag': Tag,
  'target': Target,
  'thumbs-up': ThumbsUp,
  'trash': Trash,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  'truck': Truck,
  'upload': Upload,
  'user': User,
  'user-circle': UserCircle,
  'users': Users,
  'wallet': Wallet,
  'zap': Zap,
}

/**
 * Resolve a lucide icon name (from spoke manifest) to a React component.
 * Returns Box as fallback for unknown icon names.
 */
export function resolveIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? Box
}
